package com.signaturemaker.app.application.ui.designsystem

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

@Immutable
internal object Foundation {

  val radius0: Dp = 0.dp
  val radius2: Dp = 2.dp
  val radius4: Dp = 4.dp
  val radius8: Dp = 8.dp
  val radius12: Dp = 12.dp
  val radius16: Dp = 16.dp
  val radius17: Dp = 17.dp
  val radius24: Dp = 24.dp
  val radius360: Dp = 360.dp
  val size0: Dp = 0.dp
  val size1: Dp = 1.dp
  val size2: Dp = 2.dp
  val size4: Dp = 4.dp
  val size8: Dp = 8.dp
  val size10: Dp = 10.dp
  val size12: Dp = 12.dp
  val size16: Dp = 16.dp
  val size20: Dp = 20.dp
  val size24: Dp = 24.dp
  val size32: Dp = 32.dp
  val size34: Dp = 34.dp
  val size40: Dp = 40.dp
  val size44: Dp = 44.dp
  val size48: Dp = 48.dp
  val size56: Dp = 56.dp
  val size64: Dp = 64.dp
  val size72: Dp = 72.dp
  val size80: Dp = 80.dp
  val size92: Dp = 92.dp
  val size96: Dp = 96.dp
  val size104: Dp = 104.dp
  val size112: Dp = 112.dp
  val size120: Dp = 120.dp
  val size128: Dp = 128.dp
  val size136: Dp = 136.dp
  val size140: Dp = 140.dp
  val size144: Dp = 144.dp
  val size152: Dp = 152.dp
  val size156: Dp = 156.dp
  val size160: Dp = 160.dp
  val size164: Dp = 164.dp
  val size194: Dp = 194.dp
  val size195: Dp = 195.dp
  val size200: Dp = 200.dp
  val size214: Dp = 214.dp
  val size238: Dp = 238.dp
  val size239: Dp = 239.dp
  val size328: Dp = 328.dp
  val spacing0: Dp = 0.dp
  val spacing1: Dp = 1.dp
  val spacing2: Dp = 2.dp
  val spacing4: Dp = 4.dp
  val spacing8: Dp = 8.dp
  val spacing12: Dp = 12.dp
  val spacing16: Dp = 16.dp
  val spacing24: Dp = 24.dp
  val spacing32: Dp = 32.dp
  val spacing40: Dp = 40.dp
  val spacing48: Dp = 48.dp
  val spacing56: Dp = 56.dp
  val spacing64: Dp = 64.dp
  val spacing120: Dp = 120.dp
  val spacing128: Dp = 128.dp

    val primaryLight = Color(0xFF00696C)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFF9CF1F4)
    val onPrimaryContainerLight = Color(0xFF004F52)
    val secondaryLight = Color(0xFF4A6364)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFCCE8E8)
    val onSecondaryContainerLight = Color(0xFF324B4C)
    val tertiaryLight = Color(0xFF4D5F7C)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFD5E3FF)
    val onTertiaryContainerLight = Color(0xFF354763)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFF4FBFA)
    val onBackgroundLight = Color(0xFF161D1D)
    val surfaceLight = Color(0xFFF4FBFA)
    val onSurfaceLight = Color(0xFF161D1D)
    val surfaceVariantLight = Color(0xFFDAE4E4)
    val onSurfaceVariantLight = Color(0xFF3F4949)
    val outlineLight = Color(0xFF6F7979)
    val outlineVariantLight = Color(0xFFBEC8C8)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2B3232)
    val inverseOnSurfaceLight = Color(0xFFECF2F2)
    val inversePrimaryLight = Color(0xFF80D4D7)
    val surfaceDimLight = Color(0xFFD5DBDB)
    val surfaceBrightLight = Color(0xFFF4FBFA)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFEFF5F4)
    val surfaceContainerLight = Color(0xFFE9EFEF)
    val surfaceContainerHighLight = Color(0xFFE3E9E9)
    val surfaceContainerHighestLight = Color(0xFFDDE4E3)

    val primaryLightMediumContrast = Color(0xFF003D3F)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFF16797C)
    val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryLightMediumContrast = Color(0xFF213A3B)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFF587273)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF243752)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFF5C6E8C)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF740006)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFF4FBFA)
    val onBackgroundLightMediumContrast = Color(0xFF161D1D)
    val surfaceLightMediumContrast = Color(0xFFF4FBFA)
    val onSurfaceLightMediumContrast = Color(0xFF0C1212)
    val surfaceVariantLightMediumContrast = Color(0xFFDAE4E4)
    val onSurfaceVariantLightMediumContrast = Color(0xFF2E3838)
    val outlineLightMediumContrast = Color(0xFF4B5454)
    val outlineVariantLightMediumContrast = Color(0xFF656F6F)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF2B3232)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F2)
    val inversePrimaryLightMediumContrast = Color(0xFF80D4D7)
    val surfaceDimLightMediumContrast = Color(0xFFC1C8C7)
    val surfaceBrightLightMediumContrast = Color(0xFFF4FBFA)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F4)
    val surfaceContainerLightMediumContrast = Color(0xFFE3E9E9)
    val surfaceContainerHighLightMediumContrast = Color(0xFFD8DEDE)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFCCD3D3)

    val primaryLightHighContrast = Color(0xFF003234)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF005254)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF173031)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF344D4E)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF1A2D47)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF384A66)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF600004)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF98000A)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFF4FBFA)
    val onBackgroundLightHighContrast = Color(0xFF161D1D)
    val surfaceLightHighContrast = Color(0xFFF4FBFA)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFDAE4E4)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF242E2E)
    val outlineVariantLightHighContrast = Color(0xFF414B4B)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF2B3232)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFF80D4D7)
    val surfaceDimLightHighContrast = Color(0xFFB4BABA)
    val surfaceBrightLightHighContrast = Color(0xFFF4FBFA)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFECF2F2)
    val surfaceContainerLightHighContrast = Color(0xFFDDE4E3)
    val surfaceContainerHighLightHighContrast = Color(0xFFCFD6D5)
    val surfaceContainerHighestLightHighContrast = Color(0xFFC1C8C7)

    val primaryDark = Color(0xFF80D4D7)
    val onPrimaryDark = Color(0xFF003738)
    val primaryContainerDark = Color(0xFF004F52)
    val onPrimaryContainerDark = Color(0xFF9CF1F4)
    val secondaryDark = Color(0xFFB0CCCC)
    val onSecondaryDark = Color(0xFF1B3435)
    val secondaryContainerDark = Color(0xFF324B4C)
    val onSecondaryContainerDark = Color(0xFFCCE8E8)
    val tertiaryDark = Color(0xFFB5C7E9)
    val onTertiaryDark = Color(0xFF1E314C)
    val tertiaryContainerDark = Color(0xFF354763)
    val onTertiaryContainerDark = Color(0xFFD5E3FF)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF0E1415)
    val onBackgroundDark = Color(0xFFDDE4E3)
    val surfaceDark = Color(0xFF0E1415)
    val onSurfaceDark = Color(0xFFDDE4E3)
    val surfaceVariantDark = Color(0xFF3F4949)
    val onSurfaceVariantDark = Color(0xFFBEC8C8)
    val outlineDark = Color(0xFF899393)
    val outlineVariantDark = Color(0xFF3F4949)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFDDE4E3)
    val inverseOnSurfaceDark = Color(0xFF2B3232)
    val inversePrimaryDark = Color(0xFF00696C)
    val surfaceDimDark = Color(0xFF0E1415)
    val surfaceBrightDark = Color(0xFF343A3A)
    val surfaceContainerLowestDark = Color(0xFF090F0F)
    val surfaceContainerLowDark = Color(0xFF161D1D)
    val surfaceContainerDark = Color(0xFF1A2121)
    val surfaceContainerHighDark = Color(0xFF252B2B)
    val surfaceContainerHighestDark = Color(0xFF303636)

    val primaryDarkMediumContrast = Color(0xFF96EAEE)
    val onPrimaryDarkMediumContrast = Color(0xFF002B2C)
    val primaryContainerDarkMediumContrast = Color(0xFF479DA1)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    val secondaryDarkMediumContrast = Color(0xFFC6E2E2)
    val onSecondaryDarkMediumContrast = Color(0xFF10292A)
    val secondaryContainerDarkMediumContrast = Color(0xFF7B9696)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    val tertiaryDarkMediumContrast = Color(0xFFCBDDFF)
    val onTertiaryDarkMediumContrast = Color(0xFF132640)
    val tertiaryContainerDarkMediumContrast = Color(0xFF7F92B1)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    val errorDarkMediumContrast = Color(0xFFFFD2CC)
    val onErrorDarkMediumContrast = Color(0xFF540003)
    val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF0E1415)
    val onBackgroundDarkMediumContrast = Color(0xFFDDE4E3)
    val surfaceDarkMediumContrast = Color(0xFF0E1415)
    val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkMediumContrast = Color(0xFF3F4949)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFD4DEDE)
    val outlineDarkMediumContrast = Color(0xFFAAB4B4)
    val outlineVariantDarkMediumContrast = Color(0xFF889292)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFDDE4E3)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2B)
    val inversePrimaryDarkMediumContrast = Color(0xFF005153)
    val surfaceDimDarkMediumContrast = Color(0xFF0E1415)
    val surfaceBrightDarkMediumContrast = Color(0xFF3F4646)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF040808)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF181F1F)
    val surfaceContainerDarkMediumContrast = Color(0xFF232929)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF2D3434)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF383F3F)

    val primaryDarkHighContrast = Color(0xFFB6FCFF)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFF7CD0D3)
    val onPrimaryContainerDarkHighContrast = Color(0xFF000E0E)
    val secondaryDarkHighContrast = Color(0xFFDAF5F6)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFADC8C8)
    val onSecondaryContainerDarkHighContrast = Color(0xFF000E0E)
    val tertiaryDarkHighContrast = Color(0xFFEAF0FF)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFB1C3E5)
    val onTertiaryContainerDarkHighContrast = Color(0xFF000B1E)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    val onErrorContainerDarkHighContrast = Color(0xFF220001)
    val backgroundDarkHighContrast = Color(0xFF0E1415)
    val onBackgroundDarkHighContrast = Color(0xFFDDE4E3)
    val surfaceDarkHighContrast = Color(0xFF0E1415)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF3F4949)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFE8F2F2)
    val outlineVariantDarkHighContrast = Color(0xFFBAC5C5)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFDDE4E3)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF005153)
    val surfaceDimDarkHighContrast = Color(0xFF0E1415)
    val surfaceBrightDarkHighContrast = Color(0xFF4B5151)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF1A2121)
    val surfaceContainerDarkHighContrast = Color(0xFF2B3232)
    val surfaceContainerHighDarkHighContrast = Color(0xFF363D3D)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF414848)

  // Legacy colors (mantener compatibilidad)
  val Blue: Color = Color(0xFF3F51B5)
  val Red: Color = Color(0xFFF44336)
  val Green: Color = Color(0xFF4CAF50)
  val Black: Color = Color(0xFF000000)
  val White: Color = Color(0xFFFFFFFF)
}
