package com.signaturemaker.app.application.ui.designsystem

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

@Immutable
internal object Foundation {

  val radius0: Dp = 0.dp
  val radius2: Dp = 2.dp
  val radius4: Dp = 4.dp
  val radius8: Dp = 8.dp
  val radius12: Dp = 12.dp
  val radius16: Dp = 16.dp
  val radius17: Dp = 17.dp
  val radius24: Dp = 24.dp
  val radius360: Dp = 360.dp
  val size0: Dp = 0.dp
  val size1: Dp = 1.dp
  val size2: Dp = 2.dp
  val size4: Dp = 4.dp
  val size8: Dp = 8.dp
  val size10: Dp = 10.dp
  val size12: Dp = 12.dp
  val size16: Dp = 16.dp
  val size20: Dp = 20.dp
  val size24: Dp = 24.dp
  val size32: Dp = 32.dp
  val size34: Dp = 34.dp
  val size40: Dp = 40.dp
  val size44: Dp = 44.dp
  val size48: Dp = 48.dp
  val size56: Dp = 56.dp
  val size64: Dp = 64.dp
  val size72: Dp = 72.dp
  val size80: Dp = 80.dp
  val size92: Dp = 92.dp
  val size96: Dp = 96.dp
  val size104: Dp = 104.dp
  val size112: Dp = 112.dp
  val size120: Dp = 120.dp
  val size128: Dp = 128.dp
  val size136: Dp = 136.dp
  val size140: Dp = 140.dp
  val size144: Dp = 144.dp
  val size152: Dp = 152.dp
  val size156: Dp = 156.dp
  val size160: Dp = 160.dp
  val size164: Dp = 164.dp
  val size194: Dp = 194.dp
  val size195: Dp = 195.dp
  val size200: Dp = 200.dp
  val size214: Dp = 214.dp
  val size238: Dp = 238.dp
  val size239: Dp = 239.dp
  val size328: Dp = 328.dp
  val spacing0: Dp = 0.dp
  val spacing1: Dp = 1.dp
  val spacing2: Dp = 2.dp
  val spacing4: Dp = 4.dp
  val spacing8: Dp = 8.dp
  val spacing12: Dp = 12.dp
  val spacing16: Dp = 16.dp
  val spacing24: Dp = 24.dp
  val spacing32: Dp = 32.dp
  val spacing40: Dp = 40.dp
  val spacing48: Dp = 48.dp
  val spacing56: Dp = 56.dp
  val spacing64: Dp = 64.dp
  val spacing120: Dp = 120.dp
  val spacing128: Dp = 128.dp

    val primaryLight = Color(0xFF445E91)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFD8E2FF)
    val onPrimaryContainerLight = Color(0xFF2B4678)
    val secondaryLight = Color(0xFF575E71)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFDBE2F9)
    val onSecondaryContainerLight = Color(0xFF3F4759)
    val tertiaryLight = Color(0xFF715573)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFFBD7FC)
    val onTertiaryContainerLight = Color(0xFF583E5B)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFF9F9FF)
    val onBackgroundLight = Color(0xFF1A1B20)
    val surfaceLight = Color(0xFFF9F9FF)
    val onSurfaceLight = Color(0xFF1A1B20)
    val surfaceVariantLight = Color(0xFFE1E2EC)
    val onSurfaceVariantLight = Color(0xFF44474F)
    val outlineLight = Color(0xFF75777F)
    val outlineVariantLight = Color(0xFFC4C6D0)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2F3036)
    val inverseOnSurfaceLight = Color(0xFFF0F0F7)
    val inversePrimaryLight = Color(0xFFADC6FF)
    val surfaceDimLight = Color(0xFFD9D9E0)
    val surfaceBrightLight = Color(0xFFF9F9FF)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF3F3FA)
    val surfaceContainerLight = Color(0xFFEEEDF4)
    val surfaceContainerHighLight = Color(0xFFE8E7EE)
    val surfaceContainerHighestLight = Color(0xFFE2E2E9)

    val primaryLightMediumContrast = Color(0xFF183566)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFF536DA1)
    val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryLightMediumContrast = Color(0xFF2E3647)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFF656D80)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF462D49)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFF806383)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF740006)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFF9F9FF)
    val onBackgroundLightMediumContrast = Color(0xFF1A1B20)
    val surfaceLightMediumContrast = Color(0xFFF9F9FF)
    val onSurfaceLightMediumContrast = Color(0xFF0F1116)
    val surfaceVariantLightMediumContrast = Color(0xFFE1E2EC)
    val onSurfaceVariantLightMediumContrast = Color(0xFF33363E)
    val outlineLightMediumContrast = Color(0xFF50525A)
    val outlineVariantLightMediumContrast = Color(0xFF6A6D75)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF2F3036)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F0F7)
    val inversePrimaryLightMediumContrast = Color(0xFFADC6FF)
    val surfaceDimLightMediumContrast = Color(0xFFC6C6CD)
    val surfaceBrightLightMediumContrast = Color(0xFFF9F9FF)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFF3F3FA)
    val surfaceContainerLightMediumContrast = Color(0xFFE8E7EE)
    val surfaceContainerHighLightMediumContrast = Color(0xFFDCDCE3)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFD1D1D8)

    val primaryLightHighContrast = Color(0xFF0A2B5B)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF2E487A)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF242C3D)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF41495B)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF3B233F)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF5A405D)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF600004)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF98000A)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFF9F9FF)
    val onBackgroundLightHighContrast = Color(0xFF1A1B20)
    val surfaceLightHighContrast = Color(0xFFF9F9FF)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFE1E2EC)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF292C33)
    val outlineVariantLightHighContrast = Color(0xFF464951)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF2F3036)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFFADC6FF)
    val surfaceDimLightHighContrast = Color(0xFFB8B8BF)
    val surfaceBrightLightHighContrast = Color(0xFFF9F9FF)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFF0F0F7)
    val surfaceContainerLightHighContrast = Color(0xFFE2E2E9)
    val surfaceContainerHighLightHighContrast = Color(0xFFD4D4DB)
    val surfaceContainerHighestLightHighContrast = Color(0xFFC6C6CD)

    val primaryDark = Color(0xFFADC6FF)
    val onPrimaryDark = Color(0xFF102F60)
    val primaryContainerDark = Color(0xFF2B4678)
    val onPrimaryContainerDark = Color(0xFFD8E2FF)
    val secondaryDark = Color(0xFFBFC6DC)
    val onSecondaryDark = Color(0xFF293041)
    val secondaryContainerDark = Color(0xFF3F4759)
    val onSecondaryContainerDark = Color(0xFFDBE2F9)
    val tertiaryDark = Color(0xFFDEBCDF)
    val onTertiaryDark = Color(0xFF402843)
    val tertiaryContainerDark = Color(0xFF583E5B)
    val onTertiaryContainerDark = Color(0xFFFBD7FC)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF111318)
    val onBackgroundDark = Color(0xFFE2E2E9)
    val surfaceDark = Color(0xFF111318)
    val onSurfaceDark = Color(0xFFE2E2E9)
    val surfaceVariantDark = Color(0xFF44474F)
    val onSurfaceVariantDark = Color(0xFFC4C6D0)
    val outlineDark = Color(0xFF8E9099)
    val outlineVariantDark = Color(0xFF44474F)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE2E2E9)
    val inverseOnSurfaceDark = Color(0xFF2F3036)
    val inversePrimaryDark = Color(0xFF445E91)
    val surfaceDimDark = Color(0xFF111318)
    val surfaceBrightDark = Color(0xFF37393E)
    val surfaceContainerLowestDark = Color(0xFF0C0E13)
    val surfaceContainerLowDark = Color(0xFF1A1B20)
    val surfaceContainerDark = Color(0xFF1E1F25)
    val surfaceContainerHighDark = Color(0xFF282A2F)
    val surfaceContainerHighestDark = Color(0xFF33353A)

    val primaryDarkMediumContrast = Color(0xFFCFDCFF)
    val onPrimaryDarkMediumContrast = Color(0xFF002454)
    val primaryContainerDarkMediumContrast = Color(0xFF7790C7)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    val secondaryDarkMediumContrast = Color(0xFFD5DCF3)
    val onSecondaryDarkMediumContrast = Color(0xFF1E2636)
    val secondaryContainerDarkMediumContrast = Color(0xFF8990A5)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    val tertiaryDarkMediumContrast = Color(0xFFF5D1F5)
    val onTertiaryDarkMediumContrast = Color(0xFF341D38)
    val tertiaryContainerDarkMediumContrast = Color(0xFFA687A7)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    val errorDarkMediumContrast = Color(0xFFFFD2CC)
    val onErrorDarkMediumContrast = Color(0xFF540003)
    val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF111318)
    val onBackgroundDarkMediumContrast = Color(0xFFE2E2E9)
    val surfaceDarkMediumContrast = Color(0xFF111318)
    val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkMediumContrast = Color(0xFF44474F)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFDADCE6)
    val outlineDarkMediumContrast = Color(0xFFB0B1BB)
    val outlineVariantDarkMediumContrast = Color(0xFF8E9099)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFE2E2E9)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF282A2F)
    val inversePrimaryDarkMediumContrast = Color(0xFF2C4779)
    val surfaceDimDarkMediumContrast = Color(0xFF111318)
    val surfaceBrightDarkMediumContrast = Color(0xFF43444A)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF06070C)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF1C1D22)
    val surfaceContainerDarkMediumContrast = Color(0xFF26282D)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF313238)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C3D43)

    val primaryDarkHighContrast = Color(0xFFECEFFF)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFFA9C2FC)
    val onPrimaryContainerDarkHighContrast = Color(0xFF000A22)
    val secondaryDarkHighContrast = Color(0xFFECEFFF)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFBBC2D8)
    val onSecondaryContainerDarkHighContrast = Color(0xFF040B1B)
    val tertiaryDarkHighContrast = Color(0xFFFFEAFC)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFDAB8DB)
    val onTertiaryContainerDarkHighContrast = Color(0xFF17031C)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    val onErrorContainerDarkHighContrast = Color(0xFF220001)
    val backgroundDarkHighContrast = Color(0xFF111318)
    val onBackgroundDarkHighContrast = Color(0xFFE2E2E9)
    val surfaceDarkHighContrast = Color(0xFF111318)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF44474F)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFEEEFF9)
    val outlineVariantDarkHighContrast = Color(0xFFC1C2CC)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFE2E2E9)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF2C4779)
    val surfaceDimDarkHighContrast = Color(0xFF111318)
    val surfaceBrightDarkHighContrast = Color(0xFF4E5056)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF1E1F25)
    val surfaceContainerDarkHighContrast = Color(0xFF2F3036)
    val surfaceContainerHighDarkHighContrast = Color(0xFF3A3B41)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF45474C)

    // Legacy colors (mantener compatibilidad)
  val Blue: Color = Color(0xFF3F51B5)
  val Red: Color = Color(0xFFF44336)
  val Green: Color = Color(0xFF4CAF50)
  val Black: Color = Color(0xFF000000)
  val White: Color = Color(0xFFFFFFFF)
}
